spring:
  application.name: ServiceGateway

server:
    port: 8443
    ssl:
        key-store: build/keystore.jks
        key-store-password: secret
        key-password: secret
        key-alias: selfsigned
       
    
security:
  user:
    password: 'password'
    
    

logging:
    level.org.apache.http.wire: 'DEBUG'
    level.au.com.windyroad.servicegateway: 'DEBUG'
    
au.com.windyroad.service-gateway.proxy:
    max.connections:
        total: 100
        route: 5
    read.timeout.ms: 60000