spring:
  application.name: ServiceGateway

server:
    port: 8443
    ssl:
        key-store: build/keystore.jks
        key-store-password: secret
        key-password: secret
        key-alias: selfsigned
       
    
security:
  user:
    name: 'user'
    password: 'password'
    
    

logging:
    level.org.apache.http.wire: 'DEBUG'
    level.au.com.windyroad.servicegateway: 'DEBUG'
    
server.tomcat.access-log-enabled: true